### ISSUE TITLE
Modules system in JavaScript

### ISSUE THREAD

**Issue by emer7** [se-edu/learningresources#100]
- What is modules in JavaScript
- Why use modules
- How is it implemented (IIFE/`<Script>`, CommonJS, ES6 Import/Export)
- How to choose which one to use? (TBC)
- How to get started (Babel Webpack)

Source:
https://medium.freecodecamp.org/javascript-modules-a-beginner-s-guide-783f7d7a5fcc

**Comment by damithc** [comment]
Try to follow the recommended structure, as given in the guidelines
