### ISSUE TITLE
Inconsistencies between VueJs, NodeJS and React

### ISSUE THREAD

**Issue by Tejas2805** [se-edu/learningresources#125]
The chapters on VueJs, NodeJS and React are not consistent with each other (content and structure-wise). 

Suggestion: Make all three chapters consistent structure-wise at least. And as far as possible content-wise too.

**Comment by damithc** [comment]
Yes, good to have, especially if it can be done without a lot of rewriting the content. BTW, Angular should be considered here as well?

**Comment by Tejas2805** [comment]
Okay sure. Will do for all 4 - VueJs, NodeJS, React and Angular. Is there any specific structure you prefer more or want me to use?

**Comment by damithc** [comment]
Angular and react were the more recent ones. We can follow their structure. The four articles are generally good already -- the inconsistency doesn't trouble the reader that much; so, let's limit to cosmetic changes, if any.
