### ISSUE TITLE
Introduction to Dart

### ISSUE THREAD

**Issue by le0tan** [se-edu/learningresources#126]
* Why choose Dart?
  * Smooth learning curve:
    * C-style syntax
    * script-flavored syntax sugar
    * but statically typed and support for optional nullity = much less runtime errors
    * OOP approach is so similar to Java that a lot of Java code can be directly migrated to Dart with minor changes
  * Cross-platform: runs on all major platforms
  * Three exection modes to get the best of all worlds
    * for fast development, JIT + Dart VM; 
    * for native performance: compilation to platform-specific instructions; 
    * for browser support: source-to-source compiler to JavaScript
  * Flutter uses Dart
* What is Dart?
* Dart syntax features
  * Functional programming
  * Cascade notation (..)
  * Asynchrony support
  * Java-like OOP, but less verbose
    * getter/setter
    * extension methods
    * generics
* How to learn Dart?
  * list some resources on Dart
* What's next?
  * effective Dart
  * use Dart in Flutter

**Comment by le0tan** [comment]
@damithc do I need to get approved before drafting the PR?

**Comment by damithc** [comment]
Can go ahead. Try to follow the structure of the Go chapter https://se-education.org/learningresources/contents/go/Go.html
