### ISSUE TITLE
NoSQL ft. mongoDB

### ISSUE THREAD

**Issue by ang-zeyu** [se-edu/learningresources#130]
Assumptions:
- Reader has some knowledge of relational databases; Points of comparison will be made.

Aim: Introduce the characteristics of non-relational databases, their benefits, using mongoDB as an example.

What is NoSQL?

Why NoSQL ( vs SQL )
- 'Agile' / no fixed schema - perfect for changing requirements, **real world applications**
- Horizontal scalability
- Widespread adoption as well ( e.g. amazon )

How NoSQL works ( with reference to mongoDB as an example for all points, and vs SQL )
- what is mongoDB?
- Basic structure of NoSQL databases
  - database -> collections -> documents hierachy
  - documents structure ( json )
- Basic CRUD operation examples
  - Caveats - nesting limit, document size limit
- Indexes
- Schemas in NoSQL 
- Relation storage in NoSQL ( 1-1, 1-many, many-many )
- Data processing ( mongoDB aggregation )
- Horizontal scalability ( sharding )

How to get started with NoSQL?
- Reinforce basic structure of NoSQL databases
- Basic mongoDB query language
- Advanced mongoDB processing ( aggregation, indexes, schemas, schema validation, etc )
- Advanced topics: ( Where to go from here )
  - Why NoSQL is more easily horizontally scalable
  - Redundancy in NoSQL
  - Brief mention of in-memory NoSQL db ( redis )

**Comment by ang-zeyu** [comment]
Hi prof @damithc, is this topic fine?

If it ends up to be too much for one article, I would remove the references and comparisons to SQL, which would be also more in line with the existing SQL article
A seperate article may deal with the topic of SQL vs NoSQL in the future

**Comment by damithc** [comment]
Yes @ang-zeyu but let's keep in short as we have been trying to limit to SE topics lately (although the book already has some non SE topics that were added long ago).

**Comment by ang-zeyu** [comment]
Noted 👍
