### ISSUE TITLE
Use of word 'module' in javascript/javascript-modules#module-pattern confusing

### ISSUE THREAD

**Issue by openorclose** [se-edu/learningresources#135]
Link:

https://deploy-preview-127--learningresources.netlify.com/contents/javascript/javascript-modules#module-pattern

![image](https://user-images.githubusercontent.com/3646725/73997555-ca3c6100-4999-11ea-998f-e1b7790459c6.png)

JavaScript has modules already (as described in the section directly above). While the above code does make use of the module pattern (wrapping all related code inside one global), calling that a module just adds to the confusion with the already two different module systems: ES6 modules and CommonJS modules.

I propose we change rename module pattern to ['namespace pattern'](https://www.typescriptlang.org/docs/handbook/namespaces-and-modules.html)
to better reflect what is going on: the reduction of global variables pollution by only creating one global variable, with all other functions and variables inside that object.

**Comment by damithc** [comment]
Go ahead and submit a PR @openorclose for this issue and other issues you've found.
