### ISSUE TITLE
Introduction to NLP

### ISSUE THREAD

**Issue by j-lum** [se-edu/learningresources#137]
* Introduction to Natural Language Processing 
	* What is NLP
	* Why learn NLP
		* Low barrier of entry
		* Wide array of applications
		* Unsaturated field of research
			* Advantages of being multilingual 
	* Common applications of NLP
		* Intent detection
		* Information retrival
		* Enhanced UX
		* Machine translation
		* Natural Language Generation
	* How to get started

**Comment by damithc** [comment]
I'm OK with the topic but let's keep it a short 'Outsider' look as we have been trying to limit this book to an SE resource.
