### ISSUE TITLE
Improve Best Practices with git

### ISSUE THREAD

**Issue by iskandarzulkarnaien** [se-edu/learningresources#140]
- Add more links to relevant articles
- Add more explanations for complicated/non-beginner friendly concepts or jargon (most likely using tooltips)
- Add more beginner-friendly tips (e.g. undoing accidental rebase)
- Add on more information (if any)

**Comment by damithc** [comment]
We don't want to write our own tutorial though. Instead, we prefer to guide readers to the best resources elsewhere.
