### ISSUE TITLE
Introduction to Elm

### ISSUE THREAD

**Issue by openorclose** [se-edu/learningresources#145]
A functional programming language for developing web apps that compiles to JavaScript.

Promises features like no runtime exceptions due to it being a functional programming language, and has the one of the best compiler error messages out there:
https://mobile.twitter.com/gregoryschier/status/732830868562182144?lang=bn

https://elm-lang.org/

- What Is Elm?‎
- Why Learn Elm?‎
- How to Get Started with Elm?‎

**Comment by damithc** [comment]
Follow the structure of the Go language chapter
