### ISSUE TITLE
Introduction to Spring framework

### ISSUE THREAD

**Issue by 0blivious** [se-edu/learningresources#160]
The Spring Framework is an application framework and inversion of control container for the Java platform. The framework's core features can be used by any Java application, but there are extensions for building web applications on top of the Java EE (Enterprise Edition) platform.

Proposed outline:

* What is Spring Framework
* Why learn Spring
* Core features of Spring framework
* How to get started with Spring (learning resources)

**Comment by damithc** [comment]
Go ahead @0blivious
