### ISSUE TITLE
Introducing React Hooks

### ISSUE THREAD

**Issue by niqiukun** [se-edu/learningresources#162]
Hooks are a new addition in React 16.8. The official documentation of React encourages the use of Hooks when writing new React components. Hooks allows reuse of stateful logic between components, makes components easier to understand and less confusing. 

Proposed changes:
- Change the existing code example from class component to function component
- Add a section in the Introduction to React page to introduce Hooks

**Comment by damithc** [comment]
Keep in mind that we target readers with zero React knowledge and aim to give an 'outsider-in' view of a topic; don't go too deep into React features.

**Comment by niqiukun** [comment]
React Hooks is a replacement of the traditional way of coding with class components. 

For example, the following code segments included in the topic:
```javascript
class App extends Component {
  state = {
    name: "John Doe"
  };

  handleChange = event => {
    this.setState({
      name: event.target.value
    });
  };

  render() {
    return (
      <div className="App">
        <h1>Person Data</h1>
        <PersonComponent
          name={this.state.name}
          changeHandler={this.handleChange}
        />
      </div>
    );
  }
}
```
should be replaced by:
```javascript
function App() {
  const [name, setName] = useState("John Doe");

  const handleChange = event => {
    setName(event.target.value);
  };

  return (
    <div className="App">
      <h1>Person Data</h1>
      <PersonComponent
        name={name}
        changeHandler={handleChange}
      />
    </div>
  );
}
```
The improvement in code clarity is quite obvious here.

I propose this change because it allows target readers with zero prior experience to start writing code using Hooks, the way recommemded by React, and get used to it, instead of learning about class components since class components are harder to read, have no access to potential new features introduced (although I will not introduce them here), and will eventually be obsolete in future. It is also important to develop a good coding style at the beginning and stick to it.

**Comment by damithc** [comment]
> I propose this change because it allows target readers with zero prior experience to start writing code using Hooks, the way recommemded by React, and get used to it, instead of learning about class components since class components are harder to read, have no access to potential new features introduced (although I will not introduce them here), and will eventually be obsolete in future. It is also important to develop a good coding style at the beginning and stick to it.

Yes, it is better to use the 'recommended' way in the code examples all other things being equal.

**Comment by niqiukun** [comment]
I will not add any new section to the page then and keep everything else unchanged. I will only change the code examples to the Hooks way of writing.

**Comment by damithc** [comment]
> I will not add any new section to the page then and keep everything else unchanged. I will only change the code examples to the Hooks way of writing.

Sounds good.
