### ISSUE TITLE
Use titleCase

### ISSUE THREAD

**Issue by Tejas2805** [se-edu/learningresources#164]
Based on what was said by @amad-person in #127 Let's use titleCase for headings wherever not used.

**Comment by Tejas2805** [comment]
@damithc Is it okay to proceed with this?

**Comment by damithc** [comment]
> @damithc Is it okay to proceed with this?

Sure.

**Comment by iskandarzulkarnaien** [comment]
@Tejas2805 does #166 resolve this issue or are you planning to make more PRs?

**Comment by Tejas2805** [comment]
Ah sorry. Forgot to close. #166 resolves the issue.
