### ISSUE TITLE
Insecure mixed content warning

### ISSUE THREAD

**Issue by damithc** [se-edu/learningresources#189]
Netlify is giving this warning for every build of this repo.

![image](https://user-images.githubusercontent.com/1673303/78569507-506c0b00-7856-11ea-9b3a-711bc4b9c8dc.png)

**Comment by j-lum** [comment]
I think these are from some images directly linked from http sites. Is there a log of all these instances so that we can replace them?

**Comment by damithc** [comment]
> I think these are from some images directly linked from http sites. Is there a log of all these instances so that we can replace them?

I couldn't find anything in the log. Perhaps do a site-wide search for `http:`? Or is there some tool that can help find them?

**Comment by jamessspanggg** [comment]
The log is actually available [here](https://app.netlify.com/sites/learningresources/deploys/5e94a2bc6f21210006a261d2).

The following are the mixed contents used in learning resources, but they are not available in `https`.
<img width="638" alt="Screen Shot 2020-04-14 at 1 36 30 AM" src="https://user-images.githubusercontent.com/32864116/79143762-5fbbfd00-7df0-11ea-9da0-ce6979970f35.png">

**Comment by jamessspanggg** [comment]
@damithc since they are images, should I download the images and include them within the resources? This will eliminate the error. Note that this issue is the same as #116

**Comment by damithc** [comment]
> @damithc since they are images, should I download the images and include them within the resources?

Yes, but only if their license allows it.
