### ISSUE TITLE
Missing link to repo in navBar

### ISSUE THREAD

**Issue by Tejas2805** [se-edu/learningresources#197]
![Screen Shot 2020-05-31 at 1 50 26 AM](https://user-images.githubusercontent.com/35946746/83335712-2d535a00-a2e1-11ea-937b-44dc294b1dd6.png)

Not sure, if this is intentional. But initially, there was a GitHub icon in the `navBar` linking it to the repository page.

**Comment by damithc** [comment]
Fixed. thanks for the bug report @Tejas2805
