### ISSUE TITLE
introduction-to-python.md: doesn't cover differences between versions 2.7.x and 3.x

### ISSUE THREAD

**Issue by PierceAndy** [se-edu/learningresources#34]
The introduction to Python learning resource article doesn't cover the differences between 2.7.x and 3.x.

As a piece of introductory material to Python, it might be a good idea to cover these differences.
Many beginners often question why there are two widely supported versions, and what the differences are.

(Personally I advocate the use of 3.x, and 2.7.x only for legacy reasons)

**Comment by crphang** [comment]
Since I already have a PR on improving python book chapter, I'll add this section in 👍
