### ISSUE TITLE
Password storage

### ISSUE THREAD

**Issue by ChooJeremy** [se-edu/learningresources#65]
I would like to write a chapter on storing passwords

Textbook outline:

Password storage intro
What's wrong with plaintext?
What is hashing?
Why isn't hashing enough?
Adding salt
The salted hash
If an attacker has gained access to the entire application, what does it matter if my passwords are stored in plaintext or not?
Word of warning
Further reading

**Comment by damithc** [comment]
Go ahead @ChooJeremy
