### ISSUE TITLE
Introduction to SQL

### ISSUE THREAD

**Issue by amrut-prabhu** [se-edu/learningresources#68]
Outline:
- What is SQL
- Why use SQL
- An example showing basic commands
- Getting started
- Other resources for learning and integrating SQL

**Comment by amrut-prabhu** [comment]
@damithc Is this okay?

**Comment by damithc** [comment]
Seems OK 👍 Try to follow the suggested structure as much as possible https://se-education.org/learningresources/contributing.html#guidelines-for-writing-content
