### ISSUE TITLE
Introduction to Angular

### ISSUE THREAD

**Issue by RonakLakhotia** [se-edu/learningresources#70]
Outline:

* Overview
* Advantages over other frameworks
* Disadvantages
* Present scenario in industry
* Getting started
* Other resources for learning Angular

**Comment by damithc** [comment]
Go ahead. Try to stick to the suggested structure https://se-education.org/learningresources/contributing.html#guidelines-for-writing-content

**Comment by RonakLakhotia** [comment]
Sure Prof!
