### ISSUE TITLE
Improve Swift page

### ISSUE THREAD

**Issue by Adoby7** [se-edu/learningresources#77]
Hi, I want to revise and improve the page of `Swift` to fit the guideline.

* Add `Why should learn swift` section
* Revise existing features to form different `Benefits`
* Add `Where to go from here` section
* Move some contents from `Getting start` to `Where to go from here`, and add learning path in `Getting start` section.

**Comment by damithc** [comment]
@Adoby7 go ahead

**Comment by luyangkenneth** [comment]
Closed by #90
