### ISSUE TITLE
Restructure and Add content to XSS 

### ISSUE THREAD

**Issue by ChesterSng** [se-edu/learningresources#78]
I would like to: 

- Add real life examples into the XSS page, so users can see the potential damage of the vulnerability
- Add pictures to illustrate examples 
- Improve examples 
- Add tools for testing and prevention against XSS
- Restructure the content into the recommended structure

**Comment by damithc** [comment]
Go ahead @ChesterSng. Also try to restructure the article into the recommended structure. This article was written before we introduced a specific structure for articles to follow.

**Comment by ChesterSng** [comment]
Will do so, thanks Prof @damithc!
