### ISSUE TITLE
Web Performance

### ISSUE THREAD

**Issue by marvinchin** [se-edu/learningresources#80]
Outline (will work on these progressively, unlikely to cover all aspects in the first iteration):
- [ ] Motivations for writing performant web applications
- [ ] Metrics for web performance
  - [ ] TTFB
  - [ ] TTFP
  - [ ] TTI
- [ ] Key factors to improving web performance
  - [ ] Javascript Bundle Optimisation
  - [ ] Lazy/Deferred/Progressive Loading
  - [ ] Asset Optimisation
  - [ ] Service Workers
  - [ ] Rendering Optimisation
- [ ] Measuring Web Performance
  - [ ] Audit with Lighthouse
  - [ ] Tracking RUM

**Comment by damithc** [comment]
Go ahead. Try to keep to the suggested structure. Focus on WHAT and WHY, not HOW.
