### ISSUE TITLE
Introduction to Linux Shell

### ISSUE THREAD

**Issue by junming403** [se-edu/learningresources#89]
1. What is Shell? (In specific, bash)
2. shell variables and environment
3. pipe and data redirection
4. shell script
5. to be added....

**Comment by damithc** [comment]
The target audience is Unix users? Or are you trying to persuade Windows users to use the Unix shell either by switching to Unix or using Windows 10 Unix shell?

**Comment by junming403** [comment]
Hi prof, yes, targeted audience is Unix users.

**Comment by junming403** [comment]
How to use linux is important especially in backend development as most of the servers runs on Linux.

**Comment by damithc** [comment]
Noted. But the article should focus on WHAT and WHY rather than the HOW.

**Comment by luyangkenneth** [comment]
Closed by #91
