### ISSUE TITLE
Introduction to C#

### ISSUE THREAD

**Issue by YuPeiHenry** [se-edu/learningresources#92]
* Why learn C#
* How to use new features in C# 8 to write elegant code
* Testing for C#
    * MSTest
    * NUnit

**Comment by damithc** [comment]
It may not be appropriate to give too much weight to testing in an article about C#

How about this?
* What is C#
* Why learn C#
* Some noteworthy features of C# (to provide further motivation -- C# testing facilities can be mentioned as one of the noteworthy features)
* How to get started

**Comment by YuPeiHenry** [comment]
> It may not be appropriate to give too much weight to testing in an article about C#
> 
> How about this?
> 
> * What is C#
> * Why learn C#
> * Some noteworthy features of C# (to provide further motivation -- C# testing facilities can be mentioned as one of the noteworthy features)
> * How to get started

Ok, will do the above mentioned. Will let you know if I wish to add something beyond what is listed.
