### ISSUE TITLE
Introduction to Ruby on Rails

### ISSUE THREAD

**Issue by AyushChatto** [se-edu/learningresources#95]
1. What is Ruby on Rails
2. Why should you use it all
3. What situations to use it in (and which ones you shouldn't)
4. Getting started with a simple app.
5. Further Reading

**Comment by luyangkenneth** [comment]
I've some experience with rails so I'm keen to take a look whenever this is ready for review 🙂

**Comment by AyushChatto** [comment]
@luyangkenneth I'll be sure to ask for your review when I'm done :D
