### ISSUE TITLE
Introduction to Testing in Java with JUnit 5

### ISSUE THREAD

**Issue by sijie123** [se-edu/learningresources#97]
Rationale:
We currently do not have any resources directed at testing with JUnit 5. The SE-EDU Software Engineering for Self-Directed Learners book covers principles of testing (e.g. using stubs, differentiating between unit, integration and system tests), but does not cover how to write unit tests that make use of JUnit 5's powerful API library.
JUnit 5 has a wonderful user guide in place already, but (as I learnt from personal experience) the numerous terminologies would make it difficult for a new learner to Software Engineering to understand and make full use of the API.
Hence, I wish to write a book chapter that leverages on examples (that will be added to AB4 in the near future) and which bridges the theory in SE-EDU book with actual practice. This aims to be a good starting point of reference for future students aiming to write unit tests for a SE project in Java.

Outline:
* What is JUnit 5
* Basic JUnit 5 tests
* Before/After methods and their use cases
* JUnit 5 extension model

**Comment by damithc** [comment]
Good topic. 
Do not go too deep though. The purpose of the article is to motivate and guide the reader to learn JUnit 5, not to teach JUnit 5 to the reader.
Also, don't customize to se-edu developers. it's a bonus if the article fits them, but stay true to the objective of the learningresources.
